customgpt/app/integrations/models.py
from app import db

bots_integrations = db.Table(
    "bots_integrations",
    db.Model.metadata,
    db.Column("integration_id", db.Integer, db.ForeignKey("integrations.id")),
    db.Column("bot_id", db.Integer, db.ForeignKey("bots.id")),
)


# Модель интеграции бота
class Integration(db.Model):
    __tablename__ = "integrations"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)

    bots = db.relationship("Bot", secondary=bots_integrations, back_populates="integrations")

customgpt/app/integrations/telegram/models.py
from app import db


class TelegramIntegration(db.Model):
    __tablename__ = "telegram_integrations"

    id = db.Column(db.Integer, primary_key=True)
    token = db.Column(db.String, nullable=False)
    bot_id = db.Column(db.Integer, db.ForeignKey("bots.id"), nullable=False)

customgpt/app/integrations/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from wtforms.fields.simple import StringField
from wtforms.validators import Regexp


class TelegramForm(FlaskForm):
    token = StringField("API токен", validators=[Regexp("^\d+:[a-zA-Z0-9_-]{35}$", message="Неверный токен")])
    submit = SubmitField("Сохранить")

customgpt/app/integrations/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from app.integrations.forms import TelegramForm
from app.integrations.telegram.dao import TelegramDAO
from app.integrations.telegram.telegram import create_and_run_bot

integration = Blueprint("integrations", __name__)


@integration.route("/integration")
@login_required
def integration_page():
    bot_id = request.args.get("bot_id")

    return render_template(
        "integrations/integration.html", bot_id=bot_id, username=current_user.username, email=current_user.email
    )


@integration.route("/telegram_integration/<int:bot_id>", methods=["GET", "POST"])
@login_required
def telegram_integration(bot_id):
    form = TelegramForm()
    if form.validate_on_submit():
        TelegramDAO.add_integration(bot_id, token=form.token.data)
        create_and_run_bot(bot_id)
        return redirect(url_for("projects.setting_bot", bot_id=bot_id))

    return render_template(
        "integrations/telegram_integration.html",
        bot_id=bot_id,
        username=current_user.username,
        email=current_user.email,
        form=form,
    )

customgpt/app/templates/integrations/integration.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ bot_name }}</title>
    <!-- Подключение Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900&display=swap"
          rel="stylesheet">
</head>
<body>

<div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    {% include 'projects/sidebar_setting_bot.html' %}
    <!-- /#sidebar-wrapper -->

    <!-- Информация о пользователе в сайдбаре -->
    <div class="sidebar-footer d-flex align-items-center p-3">
        <img src="{{ url_for('static', filename='Image/Frame.svg') }}" alt="User Icon" class="icon">
        <div class="user-info">
            <span class="user-name">{{ username }}</span><br>
            <span class="user-email">{{ email }}</span>
        </div>
        <a href="{{ url_for('auth.logout') }}" class="logout-icon ms-auto">
            <img src="{{ url_for('static', filename='Image/Login 3.svg') }}" alt="Logout Icon">
        </a>
    </div>

    <!-- Main Content -->
    <div class="container mt-4">
        <div class="row">
            <!-- Первый блок -->
            <div class="col-md-4 col-sm-12">
                <div class="integration-card" onclick="redirectToIntegrationInfo('{{ bot_id }}')">
                    <img src="{{ url_for('static', filename='Image/telegram-svgrepo-com 1.svg') }}" alt="Telegram">
                    <h5>Телеграм</h5>
                    <p>Подключите Телеграм для взаимодействия с вашими клиентами через наш сервис.</p>
                    {% if is_connected %}
                        <button class="btn btn-connected" disabled>
                            Подключено
                        </button>
                    {% else %}
                        <a href="{{ url_for('integrations.telegram_integration', bot_id=bot_id) }}"
                           class="btn btn-connect">
                            Подключить Телеграм
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-chevron-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M4.646 1.646a.5.5 0 0 1 0 .708L9.293 7l-4.647 4.646a.5.5 0 0 1-.708-.708L8.293 7 3.938 2.354a.5.5 0 1 1 .708-.708z"/>
                            </svg>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Подключение Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


</body>
</html>

customgpt/app/templates/integrations/telegram_integration.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ bot_name }}</title>
    <!-- Подключение Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900&display=swap"
          rel="stylesheet">
</head>
<body>

<div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    {% include 'projects/sidebar_setting_bot.html' %}
    <!-- /#sidebar-wrapper -->

    <!-- Информация о пользователе в сайдбаре -->
    <div class="sidebar-footer d-flex align-items-center p-3">
        <img src="{{ url_for('static', filename='Image/Frame.svg') }}" alt="User Icon" class="icon">
        <div class="user-info">
            <span class="user-name">{{ username }}</span><br>
            <span class="user-email">{{ email }}</span>
        </div>
        <a href="{{ url_for('auth.logout') }}" class="logout-icon ms-auto">
            <img src="{{ url_for('static', filename='Image/Login 3.svg') }}" alt="Logout Icon">
        </a>
    </div>

    <!-- Main Content -->
    <div id="page-content-wrapper" class="flex-grow-1 p-4">
        <div class="container">
            <!-- Кнопка "Назад" и заголовок "Интеграции" -->
            <div class="d-flex align-items-center mb-5 bot-name-container">
                <button onclick="history.back()" class="btn btn-link text-dark me-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         class="bi bi-chevron-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M11.354 1.646a.5.5 0 0 1 0 .708L6.707 7l4.647 4.646a.5.5 0 0 1-.708.708l-5-5a.5.5 0 0 1 0-.708l5-5a.5.5 0 0 1 .708 0z"/>
                    </svg>
                </button>
                <h2 class="display-4 mb-0">Интеграции</h2>
            </div>

            <!-- Инструкция по получению токена для Телеграм -->
            <div class="mb-4">
                <p>Для получения токена перейдите по ссылке в официальный бот Телеграм - <a
                        href="https://t.me/BotFather" target="_blank">@botfather</a> и выполните там команду <code>/newbot</code>.
                    Далее напишите имя бота, после чего напишите ссылку бота с окончанием "bot", и <a
                            href="https://t.me/BotFather" target="_blank">@botfather</a> выдаст вам токен.</p>
            </div>

            <!-- Поле для ввода API токена -->
            <form method="POST">
                {{ form.csrf_token }}
                <h4>{{ form.token.label }}</h4>
                <div class="mb-3">
                    {{ form.token(class="form-control", placeholder="Введите ваш API токен") }}
                </div>

                <!-- Скрытое поле для bot_id -->
                <input type="hidden" id="bot-id" value="{{ bot_id }}">

                <!-- Кнопка Сохранить, выровненная справа -->
                <div class="text-end">
                    {{ form.submit(class="btn btn-save") }}
                </div>
            </form>
            <!-- Сообщение об успешной или неудачной интеграции -->
            <div id="result-message" class="mt-3"></div>
        </div>
    </div>
</div>

<!-- Подключение Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>