customgpt/app/projects/models.py
from datetime import datetime

from sqlalchemy import Column, String

from app import db
from app.integrations.models import bots_integrations


# Модель бота
class Bot(db.Model):
    __tablename__ = "bots"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    status = Column(String, nullable=False, default="остановлен")  # Статус бота: работает, остановлен, ошибка
    instructions = db.Column(db.String, nullable=True)
    temperature = db.Column(db.Float, default=0.5)

    config_name = db.Column(db.String)

    file_names = db.Column(db.String)  # Имена файлов

    chat_model_id = db.Column(db.Integer, db.ForeignKey("chat_models.id"))

    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)

    def __repr__(self):
        return f"<Bot {self.name}, Status: {self.status}>"

    # Связь с пользователем (владелец бота)
    user = db.relationship("User", back_populates="bots")
    integrations = db.relationship("Integration", secondary=bots_integrations, back_populates="bots")
    chat_model = db.relationship("ChatModel", back_populates="bots")


# Модель для таблицы вопросов и ответов
class QuestionAnswer(db.Model):
    __tablename__ = "questions_answers"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    question = db.Column(db.Text, nullable=False)
    answer = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<QuestionAnswer(id={self.id}, question={self.question}, answer={self.answer})>"

    user = db.relationship("User", back_populates="questions_answers")

customgpt/app/analytics/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

# Создаём blueprint для аналитики
analytic = Blueprint("analytic", __name__)


@analytic.route("/analytic")
@login_required
def analytic_page():
    return render_template("analytics/analytic.html")

customgpt/app/integrations/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from app.integrations.forms import TelegramForm
from app.integrations.telegram.dao import TelegramDAO
from app.integrations.telegram.telegram import create_and_run_bot

integration = Blueprint("integrations", __name__)


@integration.route("/integration")
@login_required
def integration_page():
    bot_id = request.args.get("bot_id")

    return render_template(
        "integrations/integration.html", bot_id=bot_id, username=current_user.username, email=current_user.email
    )


@integration.route("/telegram_integration/<int:bot_id>", methods=["GET", "POST"])
@login_required
def telegram_integration(bot_id):
    form = TelegramForm()
    if form.validate_on_submit():
        TelegramDAO.add_integration(bot_id, token=form.token.data)
        create_and_run_bot(bot_id)
        return redirect(url_for("projects.setting_bot", bot_id=bot_id))

    return render_template(
        "integrations/telegram_integration.html",
        bot_id=bot_id,
        username=current_user.username,
        email=current_user.email,
        form=form,
    )

customgpt/app/projects/routes.py
from datetime import datetime

import pytz
from flask import Blueprint, flash, jsonify, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from app import db
from app.ai_models.dao import choose_model
from app.ai_models.models import ChatModel
from app.projects.dao import ProjectDAO
from app.projects.models import Bot, QuestionAnswer
from app.users.models import User

from .utils import DummyForm, allowed_file, extract_faq_from_pdf, get_uploaded_files

blueprint = Blueprint("projects", __name__)


@blueprint.route("/all_projects")
@login_required
def all_projects():
    """Страница со списком всех проектов пользователя."""
    # Получаем информацию о пользователе через SQLAlchemy ORM
    user = current_user
    if not user:
        flash("Ошибка при загрузке данных пользователя.", "danger")
        return redirect(url_for("auth.login"))

    username, email = user.username, user.email  # Извлекаем имя и email

    # Получаем список ботов
    bots = ProjectDAO.get_user_bots(user.id)

    # Передаем username и email в шаблон
    return render_template("projects/all_projects.html", bots=bots, username=username, email=email)


@blueprint.route("/create", methods=["POST"])
@login_required
def create_bot():
    """Маршрут для создания нового бота пользователем."""
    user_id = current_user.id
    data = request.json
    bot_name = data.get("name")

    if not bot_name:
        return jsonify({"success": False, "message": "Название бота не может быть пустым."})

    # Проверяем, существует ли уже бот с таким же именем у этого пользователя через SQLAlchemy
    existing_bot = Bot.query.filter_by(user_id=user_id, name=bot_name).first()

    if existing_bot:
        return jsonify(
            {"success": False, "message": "Бот с таким названием уже существует. Пожалуйста, выберите другое имя."}
        )

    # Создаем нового бота через SQLAlchemy ORM
    new_bot = Bot(user_id=user_id, name=bot_name, created_at=datetime.now(pytz.utc))

    try:
        db.session.add(new_bot)
        db.session.commit()  # Сохраняем изменения в базе данных

        # Получаем id нового бота для перенаправления
        redirect_url = url_for("projects.setting_bot", bot_id=new_bot.id)
        return jsonify(
            {"success": True, "message": "Бот успешно создан!", "bot_id": new_bot.id, "redirect_url": redirect_url}
        )
    except Exception as e:
        db.session.rollback()  # Откат транзакции в случае ошибки
        return jsonify({"success": False, "message": f"Не удалось создать бота. Ошибка: {e!s}"})


# projects
@blueprint.route("/delete_bot/<int:bot_id>", methods=["POST", "GET"])  # Добавляем GET для редиректа
@login_required
def delete_bot(bot_id):
    """Маршрут для удаления бота."""
    # Проверяем, существует ли бот с данным ID через SQLAlchemy
    bot = Bot.query.filter_by(id=bot_id).first()
    if not bot:
        flash("Бот с указанным ID не существует.", "danger")
        return redirect(url_for("projects.all_projects"))

    # Удаляем бота из базы данных
    try:
        db.session.delete(bot)
        db.session.commit()  # Коммитим изменения в базе данных
        flash("Бот успешно удален!", "success")
        print("Вроде ок")
    except Exception as e:
        db.session.rollback()  # Откат транзакции при ошибке
        flash(f"Ошибка при удалении бота: {e!s}", "danger")

    return redirect(url_for("projects.all_projects"))


@blueprint.route("/chatbot/<int:bot_id>", methods=["POST"])
@login_required
def chatbot(bot_id):
    user_input = request.form.get("message")
    user_id = current_user.id
    print(f"Received user input: {user_input}")  # Логируем ввод пользователя

    if user_input:
        # Загрузка текущих настроек бота из базы данных через SQLAlchemy
        bot = Bot.query.filter_by(id=bot_id).first()
        if bot:
            bot_instructions = bot.instructions
            temperature = bot.temperature
            chat_model = ChatModel.query.filter_by(id=bot.chat_model_id).first()
        else:
            chat_model = ChatModel.query.filter_by(id=1).first()
            bot_instructions, temperature = "", 0.5  # Значения по умолчанию

        # Запрос к модели через функцию get_model_response
        chat = choose_model(chat_model.name)
        context = ProjectDAO.get_user_questions(user_id)
        thread_id = f"{bot_id}"  # Получать thread_id надо из интеграций
        generated_text = chat.get_model_response(user_input, thread_id, bot_instructions, context, temperature)
        print(f"Generated text: {generated_text}")  # Логируем сгенерированный текст

        return jsonify({"response": generated_text})

    print("No input provided")  # Логируем отсутствие ввода
    return jsonify({"response": "No input provided"}), 400


@blueprint.route("/setting_bot/<int:bot_id>", methods=["GET", "POST"])
@login_required
def setting_bot(bot_id: int):
    """Маршрут для настроек бота."""
    session["bot_id"] = bot_id  # Сохраняем bot_id в сессии
    form = DummyForm()  # CSRF защита

    # Проверка существования бота
    bot = db.session.query(Bot).filter_by(id=bot_id).first()
    if not bot:
        flash("Бот с таким ID не существует.", "danger")
        return redirect(url_for("projects.all_projects"))

    bot_name = bot.name

    # Получение данных о пользователе
    user_id = current_user.id
    if user_id:
        user = db.session.query(User).filter_by(id=user_id).first()
        if user:
            username = user.username
            email = user.email
        else:
            flash("Не удалось загрузить данные пользователя.", "danger")
            return redirect(url_for("auth.login"))
    else:
        flash("Вы не авторизованы. Пожалуйста, войдите в систему.", "warning")
        return redirect(url_for("auth.login"))

    # Получаем список файлов для текущего бота
    file_list = get_uploaded_files(bot_id)

    # Получаем список моделей из таблицы select_model
    models = db.session.query(ChatModel).all()
    model_list = [{"id": model.id, "model_name": model.name} for model in models]

    if request.method == "POST":
        selected_model_id = request.form.get("model_id")
        if selected_model_id:
            selected_model_id = int(selected_model_id)
        else:
            selected_model_id = 1  # Значение по умолчанию

        # Обработка загруженного файла
        file = request.files.get("infoFile")
        all_text = []
        filename = None

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            qa_pairs = extract_faq_from_pdf(file, user_id)

            # Вставляем данные в таблицу QuestionAnswer для данного user_id
            for question, answer in qa_pairs:
                new_qa = QuestionAnswer(
                    user_id=user_id,  # Привязка к конкретному пользователю
                    question=question,
                    answer=answer,
                )
                db.session.add(new_qa)

            db.session.commit()

            flash(f"{qa_pairs} FAQ успешно извлечены из файла.", "success")

        bot_instructions = "\n".join(all_text)
        bot_more_info = request.form.get("botMoreInfo", "")
        temperature = float(request.form.get("temperature", 0.5))
        current_time = datetime.now(pytz.utc)

        # Проверка существования записи в bot_settings
        bot = db.session.query(Bot).filter_by(id=bot_id).first()

        if bot:
            # Обновление существующих настроек
            bot.info = bot_instructions
            bot.instructions = bot_more_info
            bot.temperature = temperature
            bot.file_names = filename
            bot.chat_model_id = selected_model_id
            bot.created_at = current_time
            flash("Настройки успешно обновлены!", "success")
        else:
            # Создание новых настроек
            new_bot = Bot(
                id=bot_id,
                name=bot_name,
                instructions=bot_instructions,
                temperature=temperature,
                created_at=current_time,
                file_name=filename,
                chat_model_id=selected_model_id,
            )
            db.session.add(new_bot)
            flash("Настройки успешно сохранены!", "success")

        # Логика обновления связи между ботом и моделью
        chat_model = db.session.query(ChatModel).filter_by(id=selected_model_id).first()

        if chat_model:
            bot.chat_model_id = selected_model_id
            print(bot.chat_model_id, bot)
            print(f"Запись для бота {bot_name} обновлена на модель ID {selected_model_id}.")
        else:
            new_link = Bot(id=bot_id, chat_model_id=selected_model_id)
            db.session.add(new_link)
            print(f"Запись для бота {bot_name} добавлена с моделью ID {selected_model_id}.")

        db.session.commit()  # Сохраняем изменения в базе данных
        return redirect(url_for("projects.setting_bot", bot_id=bot_id))

    # Если запрос GET, загружаем текущие настройки для отображения в форме
    bot = db.session.query(Bot).filter_by(id=bot_id).first()

    if bot:
        bot_instructions = bot.instructions
        temperature = bot.temperature
        selected_model_id = bot.chat_model
    else:
        bot_instructions, temperature, selected_model_id = "", 0.5, 1

    # Получаем текущую модель
    # current_model = db.session.query(Bot).join(Bot, Bot.id == Bot.model_id).filter(Bot.id == bot_id).first()
    #
    # if current_model:
    #     selected_model_id = current_model.id
    # else:
    #     selected_model_id = 1  # ID модели по умолчанию (Chat GPT 3.5)

    return render_template(

customgpt/app/templates/projects/all_projects.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Все проекты</title>
    <!-- Подключение Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='all_projects.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

     <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>

<body>

<div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    {% include 'sidebar.html' %}
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper" class="flex-grow-1 p-4">
        <div class="container mt-4">
    <h2 class="mb-4">Все проекты</h2>

    {% if bots %}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Статус</th>
                    <th scope="col">Имя бота</th>
                    <th scope="col">Тариф</th>
                    <th scope="col">Отправлено сообщений</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for bot in bots %}
                <tr>
                    <!-- Статус -->
                    <td>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="statusSwitch{{ bot[0] }}" checked>
                        </div>
                    </td>

                    <!-- Имя бота -->
                    <td>{{ bot[1] }}</td>

                    <!-- Тариф -->
                    <td>Пробный тариф до 03.05.2024</td>

                    <!-- Аудитория -->
                    <td>10</td>

                    <!-- Кнопка действий -->
                    <!-- Кнопка действий -->
<td>
    <div class="dropdown">
        <button class="btn btn-light" type="button" id="dropdownMenuButton{{ bot[0] }}" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ url_for('static', filename='Image/ellipsis-h.svg') }}" alt="Действия">
        </button>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton{{ bot[0] }}">
            <li>
               <a class="dropdown-item" href="{{ url_for('projects.setting_bot', bot_id=bot[0]) }}">
                    <img src="{{ url_for('static', filename='Image/pen.svg') }}" alt="Редактировать" style="width: 16px; height: 16px; margin-right: 8px;">
                    Редактировать
                </a>
            </li>
            <li>
    <a class="dropdown-item text-danger" href="#" onclick="setBotIdToDelete({{ bot[0] }})" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">
        <img src="{{ url_for('static', filename='Image/trash-alt.svg') }}" alt="Удалить" style="width: 16px; height: 16px; margin-right: 8px;">
        Удалить
    </a>
</li>
        </ul>
    </div>
</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>У вас пока нет ботов. Создайте первого!</p>
    {% endif %}
</div>
    </div>
    <!-- /#page-content-wrapper -->
</div>

<!-- Модальное окно для подтверждения удаления -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Подтвердите удаление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Вы уверены, что хотите удалить этого бота? Это действие необратимо.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-danger" id="confirmDeleteButton">Удалить</button>
            </div>
        </div>
    </div>
</div>

<!-- Подключение Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.getElementById('menu-toggle').addEventListener('click', function () {
        document.getElementById('wrapper').classList.toggle('toggled');
    });
</script>

<script>
      var botIdToDelete = null;

    // Функция для установки ID бота, которого нужно удалить
    function setBotIdToDelete(botId) {
        botIdToDelete = botId;
    }

    // Когда пользователь нажимает кнопку подтверждения удаления
    document.getElementById('confirmDeleteButton').addEventListener('click', function () {
        if (botIdToDelete) {
            // Перенаправляем пользователя для удаления бота
            window.location.href = '/projects/delete_bot/' + botIdToDelete;
        }
    });
</script>

</body>
</html>

customgpt/app/templates/projects/sidebar_setting_bot.html
<div class="bg-white border-end" id="sidebar-wrapper">
    <div class="sidebar-heading d-flex justify-content-between align-items-center p-3">
        <img id="logo-text" src="{{ url_for('static', filename='Image/Logo.svg') }}" alt="CustomGPT Logo" class="logo">
        <button class="btn btn-link p-0" id="menu-toggle">
            <img src="{{ url_for('static', filename='Image/nav.svg') }}" alt="Toggle Menu">
        </button>
    </div>

    <hr class="menu-divider">

    <!-- Контейнер для меню с отступами -->
    <div class="menu-container px-3"> <!-- Добавлен класс menu-container с отступами -->
        <div class="list-group list-group-flush">
    <!-- Пункт меню "Настройки" -->
<a href="{{ url_for('projects.setting_bot', bot_id=bot_id) }}"
   class="list-group-item list-group-item-action d-flex align-items-center {% if request.path.startswith('/bot/setting_bot') %} active {% endif %}">
    <img src="{{ url_for('static', filename='Image/Cost_icon.svg') }}" alt="Настройки" class="icon">
    <span class="menu-text">Настройки</span>
</a>
<!-- Пункт меню "Интеграции" -->
<a href="{{ url_for('integrations.integration_page', bot_id=bot_id) }}"
   class="list-group-item list-group-item-action d-flex align-items-center {% if request.path.startswith('/integrations/integration') %} active {% endif %}">
    <img src="{{ url_for('static', filename='Image/Cost_icon.svg') }}" alt="Интеграции" class="icon">
    <span class="menu-text">Интеграции</span>
</a>
    <a href="{{ url_for('analytic.analytic_page') }}"
   class="list-group-item list-group-item-action d-flex align-items-center {% if request.path.startswith('/analytic') %} active {% endif %}">
    <img src="{{ url_for('static', filename='Image/Cost_icon.svg') }}" alt="Аналитика" class="icon">
    <span class="menu-text">Аналитика</span>
</a>
        </div>
    </div>

    <!-- Добавляем разделительную линию перед блоком с пользователем -->
    <hr class="menu-divider user-divider">


    <!-- Блок с информацией о пользователе -->
    <div class="sidebar-footer d-flex align-items-center p-3">
        <img src="{{ url_for('static', filename='Image/Frame.svg') }}" alt="User Icon" class="icon">
        <div class="user-info">
            <span class="user-name">{{ username }}</span><br>
            <span class="user-email">{{ email }}</span>
        </div>
        <a href="{{ url_for('auth.logout') }}" class="logout-icon ms-auto">
            <img src="{{ url_for('static', filename='Image/Login 3.svg') }}" alt="Logout Icon">
        </a>
    </div>
</div>